// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: grpc.proto

package grpc_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GRPCService_UploadVTTFiles_FullMethodName    = "/GRPCService/UploadVTTFiles"
	GRPCService_DownloadAudioFile_FullMethodName = "/GRPCService/DownloadAudioFile"
	GRPCService_UploadVideo_FullMethodName       = "/GRPCService/UploadVideo"
)

// GRPCServiceClient is the client API for GRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCServiceClient interface {
	UploadVTTFiles(ctx context.Context, in *UploadVTTFilesRequest, opts ...grpc.CallOption) (*UploadVTTFilesResponse, error)
	DownloadAudioFile(ctx context.Context, in *VideoInfoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioFileChunk], error)
	UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadVideoRequest, UploadVideoResponse], error)
}

type gRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCServiceClient(cc grpc.ClientConnInterface) GRPCServiceClient {
	return &gRPCServiceClient{cc}
}

func (c *gRPCServiceClient) UploadVTTFiles(ctx context.Context, in *UploadVTTFilesRequest, opts ...grpc.CallOption) (*UploadVTTFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadVTTFilesResponse)
	err := c.cc.Invoke(ctx, GRPCService_UploadVTTFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCServiceClient) DownloadAudioFile(ctx context.Context, in *VideoInfoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioFileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GRPCService_ServiceDesc.Streams[0], GRPCService_DownloadAudioFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VideoInfoRequest, AudioFileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCService_DownloadAudioFileClient = grpc.ServerStreamingClient[AudioFileChunk]

func (c *gRPCServiceClient) UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadVideoRequest, UploadVideoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GRPCService_ServiceDesc.Streams[1], GRPCService_UploadVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadVideoRequest, UploadVideoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCService_UploadVideoClient = grpc.ClientStreamingClient[UploadVideoRequest, UploadVideoResponse]

// GRPCServiceServer is the server API for GRPCService service.
// All implementations must embed UnimplementedGRPCServiceServer
// for forward compatibility.
type GRPCServiceServer interface {
	UploadVTTFiles(context.Context, *UploadVTTFilesRequest) (*UploadVTTFilesResponse, error)
	DownloadAudioFile(*VideoInfoRequest, grpc.ServerStreamingServer[AudioFileChunk]) error
	UploadVideo(grpc.ClientStreamingServer[UploadVideoRequest, UploadVideoResponse]) error
	mustEmbedUnimplementedGRPCServiceServer()
}

// UnimplementedGRPCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGRPCServiceServer struct{}

func (UnimplementedGRPCServiceServer) UploadVTTFiles(context.Context, *UploadVTTFilesRequest) (*UploadVTTFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadVTTFiles not implemented")
}
func (UnimplementedGRPCServiceServer) DownloadAudioFile(*VideoInfoRequest, grpc.ServerStreamingServer[AudioFileChunk]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadAudioFile not implemented")
}
func (UnimplementedGRPCServiceServer) UploadVideo(grpc.ClientStreamingServer[UploadVideoRequest, UploadVideoResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadVideo not implemented")
}
func (UnimplementedGRPCServiceServer) mustEmbedUnimplementedGRPCServiceServer() {}
func (UnimplementedGRPCServiceServer) testEmbeddedByValue()                     {}

// UnsafeGRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCServiceServer will
// result in compilation errors.
type UnsafeGRPCServiceServer interface {
	mustEmbedUnimplementedGRPCServiceServer()
}

func RegisterGRPCServiceServer(s grpc.ServiceRegistrar, srv GRPCServiceServer) {
	// If the following call pancis, it indicates UnimplementedGRPCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GRPCService_ServiceDesc, srv)
}

func _GRPCService_UploadVTTFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadVTTFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCServiceServer).UploadVTTFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCService_UploadVTTFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCServiceServer).UploadVTTFiles(ctx, req.(*UploadVTTFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCService_DownloadAudioFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VideoInfoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCServiceServer).DownloadAudioFile(m, &grpc.GenericServerStream[VideoInfoRequest, AudioFileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCService_DownloadAudioFileServer = grpc.ServerStreamingServer[AudioFileChunk]

func _GRPCService_UploadVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GRPCServiceServer).UploadVideo(&grpc.GenericServerStream[UploadVideoRequest, UploadVideoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCService_UploadVideoServer = grpc.ClientStreamingServer[UploadVideoRequest, UploadVideoResponse]

// GRPCService_ServiceDesc is the grpc.ServiceDesc for GRPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GRPCService",
	HandlerType: (*GRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadVTTFiles",
			Handler:    _GRPCService_UploadVTTFiles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadAudioFile",
			Handler:       _GRPCService_DownloadAudioFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadVideo",
			Handler:       _GRPCService_UploadVideo_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
